/** Country names and codes used to match chart labels to map shapes. */
export interface CountryRecord {
  id: string;
  iso2: string;
  iso3: string;
  names: string[];
}

export const COUNTRIES: CountryRecord[] = [
  { id: "004", iso2: "AF", iso3: "AFG", names: ["Afghanistan"] },
  { id: "008", iso2: "AL", iso3: "ALB", names: ["Albania"] },
  { id: "010", iso2: "AQ", iso3: "ATA", names: ["Antarctica"] },
  { id: "012", iso2: "DZ", iso3: "DZA", names: ["Algeria"] },
  { id: "016", iso2: "AS", iso3: "ASM", names: ["American Samoa"] },
  { id: "020", iso2: "AD", iso3: "AND", names: ["Andorra"] },
  { id: "024", iso2: "AO", iso3: "AGO", names: ["Angola"] },
  { id: "028", iso2: "AG", iso3: "ATG", names: ["Antigua and Barb.", "Antigua and Barbuda"] },
  { id: "031", iso2: "AZ", iso3: "AZE", names: ["Azerbaijan"] },
  { id: "032", iso2: "AR", iso3: "ARG", names: ["Argentina"] },
  { id: "036", iso2: "AU", iso3: "AUS", names: ["Ashmore and Cartier Is.", "Australia"] },
  { id: "040", iso2: "AT", iso3: "AUT", names: ["Austria"] },
  { id: "044", iso2: "BS", iso3: "BHS", names: ["Bahamas"] },
  { id: "048", iso2: "BH", iso3: "BHR", names: ["Bahrain"] },
  { id: "050", iso2: "BD", iso3: "BGD", names: ["Bangladesh"] },
  { id: "051", iso2: "AM", iso3: "ARM", names: ["Armenia"] },
  { id: "052", iso2: "BB", iso3: "BRB", names: ["Barbados"] },
  { id: "056", iso2: "BE", iso3: "BEL", names: ["Belgium"] },
  { id: "060", iso2: "BM", iso3: "BMU", names: ["Bermuda"] },
  { id: "064", iso2: "BT", iso3: "BTN", names: ["Bhutan"] },
  { id: "068", iso2: "BO", iso3: "BOL", names: ["Bolivia", "Bolivia, Plurinational State of"] },
  { id: "070", iso2: "BA", iso3: "BIH", names: ["Bosnia", "Bosnia and Herz.", "Bosnia and Herzegovina"] },
  { id: "072", iso2: "BW", iso3: "BWA", names: ["Botswana"] },
  { id: "074", iso2: "BV", iso3: "BVT", names: ["Bouvet Island"] },
  { id: "076", iso2: "BR", iso3: "BRA", names: ["Brazil"] },
  { id: "084", iso2: "BZ", iso3: "BLZ", names: ["Belize"] },
  { id: "086", iso2: "IO", iso3: "IOT", names: ["Br. Indian Ocean Ter.", "British Indian Ocean Territory"] },
  { id: "090", iso2: "SB", iso3: "SLB", names: ["Solomon Is.", "Solomon Islands"] },
  { id: "092", iso2: "VG", iso3: "VGB", names: ["British Virgin Is.", "Virgin Islands (British)"] },
  { id: "096", iso2: "BN", iso3: "BRN", names: ["Brunei", "Brunei Darussalam"] },
  { id: "100", iso2: "BG", iso3: "BGR", names: ["Bulgaria"] },
  { id: "104", iso2: "MM", iso3: "MMR", names: ["Myanmar"] },
  { id: "108", iso2: "BI", iso3: "BDI", names: ["Burundi"] },
  { id: "112", iso2: "BY", iso3: "BLR", names: ["Belarus"] },
  { id: "116", iso2: "KH", iso3: "KHM", names: ["Cambodia"] },
  { id: "120", iso2: "CM", iso3: "CMR", names: ["Cameroon"] },
  { id: "124", iso2: "CA", iso3: "CAN", names: ["Canada"] },
  { id: "132", iso2: "CV", iso3: "CPV", names: ["Cabo Verde"] },
  { id: "136", iso2: "KY", iso3: "CYM", names: ["Cayman Is.", "Cayman Islands"] },
  { id: "140", iso2: "CF", iso3: "CAF", names: ["Central African Rep.", "Central African Republic"] },
  { id: "144", iso2: "LK", iso3: "LKA", names: ["Sri Lanka"] },
  { id: "148", iso2: "TD", iso3: "TCD", names: ["Chad"] },
  { id: "152", iso2: "CL", iso3: "CHL", names: ["Chile"] },
  { id: "156", iso2: "CN", iso3: "CHN", names: ["China"] },
  { id: "158", iso2: "TW", iso3: "TWN", names: ["Taiwan", "Taiwan, Province of China"] },
  { id: "162", iso2: "CX", iso3: "CXR", names: ["Christmas Island"] },
  { id: "166", iso2: "CC", iso3: "CCK", names: ["Cocos (Keeling) Islands", "CocosIslands"] },
  { id: "170", iso2: "CO", iso3: "COL", names: ["Colombia"] },
  { id: "174", iso2: "KM", iso3: "COM", names: ["Comoros"] },
  { id: "175", iso2: "YT", iso3: "MYT", names: ["Mayotte"] },
  { id: "178", iso2: "CG", iso3: "COG", names: ["Congo", "Congo Brazzaville", "Congo-Brazzaville", "Republic of the Congo"] },
  { id: "180", iso2: "CD", iso3: "COD", names: ["Congo Kinshasa", "Congo-Kinshasa", "Congo, Democratic Republic of the", "Dem. Rep. Congo", "Democratic Republic of the Congo", "DR Congo", "DRC"] },
  { id: "184", iso2: "CK", iso3: "COK", names: ["Cook Is.", "Cook Islands"] },
  { id: "188", iso2: "CR", iso3: "CRI", names: ["Costa Rica"] },
  { id: "191", iso2: "HR", iso3: "HRV", names: ["Croatia"] },
  { id: "192", iso2: "CU", iso3: "CUB", names: ["Cuba"] },
  { id: "196", iso2: "CY", iso3: "CYP", names: ["Cyprus"] },
  { id: "203", iso2: "CZ", iso3: "CZE", names: ["Czech Republic", "Czechia"] },
  { id: "204", iso2: "BJ", iso3: "BEN", names: ["Benin"] },
  { id: "208", iso2: "DK", iso3: "DNK", names: ["Denmark"] },
  { id: "212", iso2: "DM", iso3: "DMA", names: ["Dominica"] },
  { id: "214", iso2: "DO", iso3: "DOM", names: ["Dominican Rep.", "Dominican Republic"] },
  { id: "218", iso2: "EC", iso3: "ECU", names: ["Ecuador"] },
  { id: "222", iso2: "SV", iso3: "SLV", names: ["El Salvador"] },
  { id: "226", iso2: "GQ", iso3: "GNQ", names: ["Eq. Guinea", "Equatorial Guinea"] },
  { id: "231", iso2: "ET", iso3: "ETH", names: ["Ethiopia"] },
  { id: "232", iso2: "ER", iso3: "ERI", names: ["Eritrea"] },
  { id: "233", iso2: "EE", iso3: "EST", names: ["Estonia"] },
  { id: "234", iso2: "FO", iso3: "FRO", names: ["Faeroe Is.", "Faroe Islands"] },
  { id: "238", iso2: "FK", iso3: "FLK", names: ["Falkland Is.", "Falkland Islands", "Falkland Islands (Malvinas)", "Malvinas"] },
  { id: "239", iso2: "GS", iso3: "SGS", names: ["S. Geo. and the Is.", "South Georgia and the South Sandwich Islands"] },
  { id: "242", iso2: "FJ", iso3: "FJI", names: ["Fiji"] },
  { id: "246", iso2: "FI", iso3: "FIN", names: ["Finland"] },
  { id: "248", iso2: "AX", iso3: "ALA", names: ["Åland", "Åland Islands"] },
  { id: "250", iso2: "FR", iso3: "FRA", names: ["France"] },
  { id: "254", iso2: "GF", iso3: "GUF", names: ["French Guiana"] },
  { id: "258", iso2: "PF", iso3: "PYF", names: ["Fr. Polynesia", "French Polynesia"] },
  { id: "260", iso2: "TF", iso3: "ATF", names: ["Fr. S. Antarctic Lands", "French Southern Territories"] },
  { id: "262", iso2: "DJ", iso3: "DJI", names: ["Djibouti"] },
  { id: "266", iso2: "GA", iso3: "GAB", names: ["Gabon"] },
  { id: "268", iso2: "GE", iso3: "GEO", names: ["Georgia"] },
  { id: "270", iso2: "GM", iso3: "GMB", names: ["Gambia"] },
  { id: "275", iso2: "PS", iso3: "PSE", names: ["Palestine", "Palestine, State of"] },
  { id: "276", iso2: "DE", iso3: "DEU", names: ["Germany"] },
  { id: "288", iso2: "GH", iso3: "GHA", names: ["Ghana"] },
  { id: "292", iso2: "GI", iso3: "GIB", names: ["Gibraltar"] },
  { id: "296", iso2: "KI", iso3: "KIR", names: ["Kiribati"] },
  { id: "300", iso2: "GR", iso3: "GRC", names: ["Greece"] },
  { id: "304", iso2: "GL", iso3: "GRL", names: ["Greenland"] },
  { id: "308", iso2: "GD", iso3: "GRD", names: ["Grenada"] },
  { id: "312", iso2: "GP", iso3: "GLP", names: ["Guadeloupe"] },
  { id: "316", iso2: "GU", iso3: "GUM", names: ["Guam"] },
  { id: "320", iso2: "GT", iso3: "GTM", names: ["Guatemala"] },
  { id: "324", iso2: "GN", iso3: "GIN", names: ["Guinea"] },
  { id: "328", iso2: "GY", iso3: "GUY", names: ["Guyana"] },
  { id: "332", iso2: "HT", iso3: "HTI", names: ["Haiti"] },
  { id: "334", iso2: "HM", iso3: "HMD", names: ["Heard I. and McDonald Is.", "Heard Island and McDonald Islands"] },
  { id: "336", iso2: "VA", iso3: "VAT", names: ["Holy See", "Vatican", "Vatican City"] },
  { id: "340", iso2: "HN", iso3: "HND", names: ["Honduras"] },
  { id: "344", iso2: "HK", iso3: "HKG", names: ["Hong Kong"] },
  { id: "348", iso2: "HU", iso3: "HUN", names: ["Hungary"] },
  { id: "352", iso2: "IS", iso3: "ISL", names: ["Iceland"] },
  { id: "356", iso2: "IN", iso3: "IND", names: ["India"] },
  { id: "360", iso2: "ID", iso3: "IDN", names: ["Indonesia"] },
  { id: "364", iso2: "IR", iso3: "IRN", names: ["Iran", "Iran, Islamic Republic of"] },
  { id: "368", iso2: "IQ", iso3: "IRQ", names: ["Iraq"] },
  { id: "372", iso2: "IE", iso3: "IRL", names: ["Ireland"] },
  { id: "376", iso2: "IL", iso3: "ISR", names: ["Israel"] },
  { id: "380", iso2: "IT", iso3: "ITA", names: ["Italy"] },
  { id: "383", iso2: "XK", iso3: "XKX", names: ["Kosovo", "Republic of Kosovo"] },
  { id: "384", iso2: "CI", iso3: "CIV", names: ["Cote d'Ivoire", "Côte d'Ivoire", "Ivory Coast"] },
  { id: "388", iso2: "JM", iso3: "JAM", names: ["Jamaica"] },
  { id: "392", iso2: "JP", iso3: "JPN", names: ["Japan"] },
  { id: "398", iso2: "KZ", iso3: "KAZ", names: ["Kazakhstan"] },
  { id: "400", iso2: "JO", iso3: "JOR", names: ["Jordan"] },
  { id: "404", iso2: "KE", iso3: "KEN", names: ["Kenya"] },
  { id: "408", iso2: "KP", iso3: "PRK", names: ["DPRK", "Korea, Democratic People's Republic of", "North Korea"] },
  { id: "410", iso2: "KR", iso3: "KOR", names: ["Korea", "Korea, Republic of", "Republic of Korea", "South Korea"] },
  { id: "414", iso2: "KW", iso3: "KWT", names: ["Kuwait"] },
  { id: "417", iso2: "KG", iso3: "KGZ", names: ["Kyrgyzstan"] },
  { id: "418", iso2: "LA", iso3: "LAO", names: ["Lao People's Democratic Republic", "Laos"] },
  { id: "422", iso2: "LB", iso3: "LBN", names: ["Lebanon"] },
  { id: "426", iso2: "LS", iso3: "LSO", names: ["Lesotho"] },
  { id: "428", iso2: "LV", iso3: "LVA", names: ["Latvia"] },
  { id: "430", iso2: "LR", iso3: "LBR", names: ["Liberia"] },
  { id: "434", iso2: "LY", iso3: "LBY", names: ["Libya"] },
  { id: "438", iso2: "LI", iso3: "LIE", names: ["Liechtenstein"] },
  { id: "440", iso2: "LT", iso3: "LTU", names: ["Lithuania"] },
  { id: "442", iso2: "LU", iso3: "LUX", names: ["Luxembourg"] },
  { id: "446", iso2: "MO", iso3: "MAC", names: ["Macao"] },
  { id: "450", iso2: "MG", iso3: "MDG", names: ["Madagascar"] },
  { id: "454", iso2: "MW", iso3: "MWI", names: ["Malawi"] },
  { id: "458", iso2: "MY", iso3: "MYS", names: ["Malaysia"] },
  { id: "462", iso2: "MV", iso3: "MDV", names: ["Maldives"] },
  { id: "466", iso2: "ML", iso3: "MLI", names: ["Mali"] },
  { id: "470", iso2: "MT", iso3: "MLT", names: ["Malta"] },
  { id: "474", iso2: "MQ", iso3: "MTQ", names: ["Martinique"] },
  { id: "478", iso2: "MR", iso3: "MRT", names: ["Mauritania"] },
  { id: "480", iso2: "MU", iso3: "MUS", names: ["Mauritius"] },
  { id: "484", iso2: "MX", iso3: "MEX", names: ["Mexico"] },
  { id: "492", iso2: "MC", iso3: "MCO", names: ["Monaco"] },
  { id: "496", iso2: "MN", iso3: "MNG", names: ["Mongolia"] },
  { id: "498", iso2: "MD", iso3: "MDA", names: ["Moldova", "Moldova, Republic of"] },
  { id: "499", iso2: "ME", iso3: "MNE", names: ["Montenegro"] },
  { id: "500", iso2: "MS", iso3: "MSR", names: ["Montserrat"] },
  { id: "504", iso2: "MA", iso3: "MAR", names: ["Morocco"] },
  { id: "508", iso2: "MZ", iso3: "MOZ", names: ["Mozambique"] },
  { id: "512", iso2: "OM", iso3: "OMN", names: ["Oman"] },
  { id: "516", iso2: "NA", iso3: "NAM", names: ["Namibia"] },
  { id: "520", iso2: "NR", iso3: "NRU", names: ["Nauru"] },
  { id: "524", iso2: "NP", iso3: "NPL", names: ["Nepal"] },
  { id: "528", iso2: "NL", iso3: "NLD", names: ["Holland", "Netherlands", "Netherlands, Kingdom of the", "The Netherlands"] },
  { id: "531", iso2: "CW", iso3: "CUW", names: ["Curaçao"] },
  { id: "533", iso2: "AW", iso3: "ABW", names: ["Aruba"] },
  { id: "534", iso2: "SX", iso3: "SXM", names: ["Sint Maarten", "Sint Maarten (Dutch part)"] },
  { id: "535", iso2: "BQ", iso3: "BES", names: ["Bonaire", "Bonaire, Sint Eustatius and Saba"] },
  { id: "540", iso2: "NC", iso3: "NCL", names: ["New Caledonia"] },
  { id: "548", iso2: "VU", iso3: "VUT", names: ["Vanuatu"] },
  { id: "554", iso2: "NZ", iso3: "NZL", names: ["New Zealand"] },
  { id: "558", iso2: "NI", iso3: "NIC", names: ["Nicaragua"] },
  { id: "562", iso2: "NE", iso3: "NER", names: ["Niger"] },
  { id: "566", iso2: "NG", iso3: "NGA", names: ["Nigeria"] },
  { id: "570", iso2: "NU", iso3: "NIU", names: ["Niue"] },
  { id: "574", iso2: "NF", iso3: "NFK", names: ["Norfolk Island"] },
  { id: "578", iso2: "NO", iso3: "NOR", names: ["Norway"] },
  { id: "580", iso2: "MP", iso3: "MNP", names: ["N. Mariana Is.", "Northern Mariana Islands"] },
  { id: "581", iso2: "UM", iso3: "UMI", names: ["United States Minor Outlying Islands"] },
  { id: "583", iso2: "FM", iso3: "FSM", names: ["Micronesia", "Micronesia, Federated States of"] },
  { id: "584", iso2: "MH", iso3: "MHL", names: ["Marshall Is.", "Marshall Islands"] },
  { id: "585", iso2: "PW", iso3: "PLW", names: ["Palau"] },
  { id: "586", iso2: "PK", iso3: "PAK", names: ["Pakistan"] },
  { id: "591", iso2: "PA", iso3: "PAN", names: ["Panama"] },
  { id: "598", iso2: "PG", iso3: "PNG", names: ["Papua New Guinea"] },
  { id: "600", iso2: "PY", iso3: "PRY", names: ["Paraguay"] },
  { id: "604", iso2: "PE", iso3: "PER", names: ["Peru"] },
  { id: "608", iso2: "PH", iso3: "PHL", names: ["Philippines"] },
  { id: "612", iso2: "PN", iso3: "PCN", names: ["Pitcairn", "Pitcairn Is."] },
  { id: "616", iso2: "PL", iso3: "POL", names: ["Poland"] },
  { id: "620", iso2: "PT", iso3: "PRT", names: ["Portugal"] },
  { id: "624", iso2: "GW", iso3: "GNB", names: ["Guinea-Bissau"] },
  { id: "626", iso2: "TL", iso3: "TLS", names: ["Timor-Leste"] },
  { id: "630", iso2: "PR", iso3: "PRI", names: ["Puerto Rico"] },
  { id: "634", iso2: "QA", iso3: "QAT", names: ["Qatar"] },
  { id: "638", iso2: "RE", iso3: "REU", names: ["Réunion"] },
  { id: "642", iso2: "RO", iso3: "ROU", names: ["Romania"] },
  { id: "643", iso2: "RU", iso3: "RUS", names: ["Russia", "Russian Federation"] },
  { id: "646", iso2: "RW", iso3: "RWA", names: ["Rwanda"] },
  { id: "652", iso2: "BL", iso3: "BLM", names: ["Saint Barthélemy", "St-Barthélemy"] },
  { id: "654", iso2: "SH", iso3: "SHN", names: ["Saint Helena", "Saint Helena, Ascension and Tristan da Cunha"] },
  { id: "659", iso2: "KN", iso3: "KNA", names: ["Saint Kitts and Nevis", "St. Kitts and Nevis"] },
  { id: "660", iso2: "AI", iso3: "AIA", names: ["Anguilla"] },
  { id: "662", iso2: "LC", iso3: "LCA", names: ["Saint Lucia"] },
  { id: "663", iso2: "MF", iso3: "MAF", names: ["Saint Martin", "Saint Martin (French part)", "St-Martin"] },
  { id: "666", iso2: "PM", iso3: "SPM", names: ["Saint Pierre and Miquelon", "St. Pierre and Miquelon"] },
  { id: "670", iso2: "VC", iso3: "VCT", names: ["Saint Vincent and the Grenadines", "St. Vin. and Gren."] },
  { id: "674", iso2: "SM", iso3: "SMR", names: ["San Marino"] },
  { id: "678", iso2: "ST", iso3: "STP", names: ["Sao Tome and Principe", "São Tomé and Principe"] },
  { id: "682", iso2: "SA", iso3: "SAU", names: ["Saudi Arabia"] },
  { id: "686", iso2: "SN", iso3: "SEN", names: ["Senegal"] },
  { id: "688", iso2: "RS", iso3: "SRB", names: ["Serbia"] },
  { id: "690", iso2: "SC", iso3: "SYC", names: ["Seychelles"] },
  { id: "694", iso2: "SL", iso3: "SLE", names: ["Sierra Leone"] },
  { id: "702", iso2: "SG", iso3: "SGP", names: ["Singapore"] },
  { id: "703", iso2: "SK", iso3: "SVK", names: ["Slovakia"] },
  { id: "704", iso2: "VN", iso3: "VNM", names: ["Viet Nam", "Vietnam"] },
  { id: "705", iso2: "SI", iso3: "SVN", names: ["Slovenia"] },
  { id: "706", iso2: "SO", iso3: "SOM", names: ["Somalia"] },
  { id: "710", iso2: "ZA", iso3: "ZAF", names: ["South Africa"] },
  { id: "716", iso2: "ZW", iso3: "ZWE", names: ["Zimbabwe"] },
  { id: "724", iso2: "ES", iso3: "ESP", names: ["Spain"] },
  { id: "728", iso2: "SS", iso3: "SSD", names: ["S. Sudan", "South Sudan"] },
  { id: "729", iso2: "SD", iso3: "SDN", names: ["Sudan"] },
  { id: "732", iso2: "EH", iso3: "ESH", names: ["W. Sahara", "Western Sahara"] },
  { id: "740", iso2: "SR", iso3: "SUR", names: ["Suriname"] },
  { id: "744", iso2: "SJ", iso3: "SJM", names: ["Svalbard and Jan Mayen"] },
  { id: "748", iso2: "SZ", iso3: "SWZ", names: ["eSwatini", "Eswatini", "Swaziland"] },
  { id: "752", iso2: "SE", iso3: "SWE", names: ["Sweden"] },
  { id: "756", iso2: "CH", iso3: "CHE", names: ["Switzerland"] },
  { id: "760", iso2: "SY", iso3: "SYR", names: ["Syria", "Syrian Arab Republic"] },
  { id: "762", iso2: "TJ", iso3: "TJK", names: ["Tajikistan"] },
  { id: "764", iso2: "TH", iso3: "THA", names: ["Thailand"] },
  { id: "768", iso2: "TG", iso3: "TGO", names: ["Togo"] },
  { id: "772", iso2: "TK", iso3: "TKL", names: ["Tokelau"] },
  { id: "776", iso2: "TO", iso3: "TON", names: ["Tonga"] },
  { id: "780", iso2: "TT", iso3: "TTO", names: ["Trinidad and Tobago"] },
  { id: "784", iso2: "AE", iso3: "ARE", names: ["UAE", "United Arab Emirates"] },
  { id: "788", iso2: "TN", iso3: "TUN", names: ["Tunisia"] },
  { id: "792", iso2: "TR", iso3: "TUR", names: ["Turkey", "Türkiye"] },
  { id: "795", iso2: "TM", iso3: "TKM", names: ["Turkmenistan"] },
  { id: "796", iso2: "TC", iso3: "TCA", names: ["Turks and Caicos Is.", "Turks and Caicos Islands"] },
  { id: "798", iso2: "TV", iso3: "TUV", names: ["Tuvalu"] },
  { id: "800", iso2: "UG", iso3: "UGA", names: ["Uganda"] },
  { id: "804", iso2: "UA", iso3: "UKR", names: ["Ukraine"] },
  { id: "807", iso2: "MK", iso3: "MKD", names: ["Macedonia", "North Macedonia"] },
  { id: "818", iso2: "EG", iso3: "EGY", names: ["Egypt"] },
  { id: "826", iso2: "GB", iso3: "GBR", names: ["Britain", "England", "Great Britain", "Northern Ireland", "Scotland", "U.K.", "UK", "United Kingdom", "United Kingdom of Great Britain and Northern Ireland", "Wales"] },
  { id: "831", iso2: "GG", iso3: "GGY", names: ["Guernsey"] },
  { id: "832", iso2: "JE", iso3: "JEY", names: ["Jersey"] },
  { id: "833", iso2: "IM", iso3: "IMN", names: ["Isle of Man"] },
  { id: "834", iso2: "TZ", iso3: "TZA", names: ["Tanzania", "Tanzania, United Republic of"] },
  { id: "840", iso2: "US", iso3: "USA", names: ["U.S.", "U.S.A.", "United States", "United States of America", "USA"] },
  { id: "850", iso2: "VI", iso3: "VIR", names: ["U.S. Virgin Is.", "Virgin Islands (U.S.)"] },
  { id: "854", iso2: "BF", iso3: "BFA", names: ["Burkina Faso"] },
  { id: "858", iso2: "UY", iso3: "URY", names: ["Uruguay"] },
  { id: "860", iso2: "UZ", iso3: "UZB", names: ["Uzbekistan"] },
  { id: "862", iso2: "VE", iso3: "VEN", names: ["Venezuela", "Venezuela, Bolivarian Republic of"] },
  { id: "876", iso2: "WF", iso3: "WLF", names: ["Wallis and Futuna", "Wallis and Futuna Is."] },
  { id: "882", iso2: "WS", iso3: "WSM", names: ["Samoa"] },
  { id: "887", iso2: "YE", iso3: "YEM", names: ["Yemen"] },
  { id: "894", iso2: "ZM", iso3: "ZMB", names: ["Zambia"] },
  { id: "geo:N. Cyprus", iso2: "", iso3: "", names: ["N. Cyprus", "Northern Cyprus"] },
  { id: "geo:Somaliland", iso2: "", iso3: "", names: ["Somaliland"] },
];
