export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  LOGIN: '/login',
  REGISTER: '/register',
  PRICING: '/pricing',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  CONTACT: '/contact',
  PAYMENT_SUCCESS: '/payment/success',
  PAYMENT_CANCEL: '/payment/cancel',
  COMPANY_CREATE: '/company/create',
  CONNECTIONS: '/dashboard/connections',
  GRAPHS_NEW: '/dashboard/graphs/new',
  SETTINGS: '/settings',
  SUBSCRIPTION: '/subscription',
} as const;
